[WIP] IssuingCashier contract
cloudwalk/brlc-token pull request #15
Opened 2022-07-04 20:15 UTC by arthur-cw

This is work in progress (WIP)

2022-07-07 07:46 UTC, EvgeniiZaitsevCW requested changes
1.  It would be nice to work with naming of functions and events.
    As I understand this contract should be like PixCashier.
    In that case my naming suggestions are:
    * `IssuingCashierUpgradeable` => `CardCashierUpgradeable`
    * `cardPayment()` => `cashOut()`
    * `cardPaymentClear()` => `cashOutClear()`
    * `cardPaymentUnclear()` => `cashOutUnclear()`
    * `cardPaymentReverse()` => `cashOutReverse()`
    * `<does_not_exist>` => `cashOutConfirm()` (to burn cleared tokens).
    * `<does_not_exist>` => `cashIn()` (to move the money back to the blockchain, e.g. through an ATM).

2.  In any case we should burn tokens if they come out from the blockchain and mint them if they come in.
3.  The  `cashOutClear()` and `cashOutUnclear()` functions look redundant. Maybe we should use only `cashOutConfirm()` and `cashOutReverse()` functions. The first one if clearing was successful, the second one if it was not.

Maybe my understanding of the contract purpose is wrong, then feel free to discuss more :)

Some other remarks are below.

2022-07-07 07:46 UTC, EvgeniiZaitsevCW commented on contracts/periphery/IssuingCashierUpgradeable.sol
> +        _clearedBalances[account] = _clearedBalances[account].add(amount);
Should we also burn tokens at this step?
Or should we add some additional function to do that?

2022-07-07 07:46 UTC, EvgeniiZaitsevCW commented on contracts/periphery/IssuingCashierUpgradeable.sol
> +    event Unclear(address indexed account, uint256 amount);
This two events are not emitted in the code. Do we need them?

2022-07-07 07:46 UTC, EvgeniiZaitsevCW commented on contracts/periphery/IssuingCashierUpgradeable.sol
> +     * @dev Executes an Issuing operation transaction
Here and in similar places.
The description does not correspond the function name.
We should change the description or the function name or both, like:
```solidity
    /**
     * @dev Initiate the cash out operation by locking tokens in the contract for future clearing
     * ...
     */
    function cashOut(uint256 amount, bytes16 client_transaction_id)
```

2022-07-07 12:24 UTC, arthur-cw commented on contracts/periphery/IssuingCashierUpgradeable.sol
> +    function cardPayment(uint256 amount, bytes16 client_transaction_id)
the `client_transaction_id` is a UUID, which is 128 bits == 16 bytes :-)
Makes sense to use the `bytes32`, but the value will be padded as you've shown. I will talk to the Issuing team.

2022-07-12 08:03 UTC, EvgeniiZaitsevCW requested changes
I suggest some changes for the contract in the [issuing-cashier-contract-variant-ez](https://github.com/cloudwalk/brlc-token/blob/feat/issuing-cashier-contract-variant-ez/contracts/periphery/IssuingCashierUpgradeable.sol) branch.
The main changes:
1. Use `bytes16 clientTransactionId` as the index for all the contract operations.
2. Introduce a structure to store each payment data.
3. Fix code formatting.
4. Improve comments.

Please see and use all the code or its parts at your will.

All the comments that are started from `//EZ` should be removed in the final version. They are introduce just to comment my changes for internal purposes.

The `issuing-cashier-contract-variant-ez` branch is intended for internal discussion only and will be deleted in the future. Please do not create a PR for it.

2022-07-18 17:59 UTC, EvgeniiZaitsevCW approved these changes

2022-07-21 13:57 UTC, cwteles commented on test/periphery/CardPaymentProcessorUpgradeable.test.ts
> +  amount: number,
Codacy has a fix for the issue: [Replace `,` with `;`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
  amount: number;
```

2022-07-21 13:57 UTC, cwteles commented on test/periphery/CardPaymentProcessorUpgradeable.test.ts
> +    'CardPaymentProcessor: payment with the provided authorization ID is uncleared'
Codacy has a fix for the issue: [Replace `'CardPaymentProcessor:·payment·with·the·provided·authorization·ID·is·uncleared'` with `"CardPaymentProcessor:·payment·with·the·provided·authorization·ID·is·uncleared";`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
    "CardPaymentProcessor: payment with the provided authorization ID is uncleared";
```

2022-07-21 13:57 UTC, cwteles commented on test-utils/misc.ts
> +  if (!/^[0-9a-fA-F]+$/.test(baseString)) {
Codacy has a fix for the issue: [Unexpected character class range '0-9'. Use '\d' instead.](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
  if (!/^[\da-fA-F]+$/.test(baseString)) {
```

2022-07-21 13:57 UTC, cwteles commented on test/periphery/CardPaymentProcessorUpgradeable.test.ts
> +    'CardPaymentProcessor: input array of authorization IDs is empty';
Codacy has a fix for the issue: [Replace `'CardPaymentProcessor:·input·array·of·authorization·IDs·is·empty'` with `"CardPaymentProcessor:·input·array·of·authorization·IDs·is·empty"`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
    "CardPaymentProcessor: input array of authorization IDs is empty";
```

2022-07-21 13:57 UTC, cwteles commented on test-utils/misc.ts
> +      + `The base string: '${baseString}'`
Codacy has a fix for the issue: [Replace `+·`The·base·string:·'${baseString}'`` with `··`The·base·string:·'${baseString}'`·+`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
        `The base string: '${baseString}'` +
```

2022-07-21 13:57 UTC, cwteles commented on test/periphery/CardPaymentProcessorUpgradeable.test.ts
> +    'CardPaymentProcessor: payment with the provided authorization ID already exists and was not revoked';
Codacy has a fix for the issue: [Replace `'CardPaymentProcessor:·payment·with·the·provided·authorization·ID·already·exists·and·was·not·revoked'` with `"CardPaymentProcessor:·payment·with·the·provided·authorization·ID·already·exists·and·was·not·revoked"`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
    "CardPaymentProcessor: payment with the provided authorization ID already exists and was not revoked";
```

2022-07-21 13:57 UTC, cwteles commented on test/periphery/CardPaymentProcessorUpgradeable.test.ts
> +const ZERO_BYTES16_STRING: string = createBytesString('00', BYTES16_LENGTH);
Codacy has a fix for the issue: [Replace `'00'` with `"00"`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
const ZERO_BYTES16_STRING: string = createBytesString("00", BYTES16_LENGTH);
```

2022-07-21 13:57 UTC, cwteles commented on test-utils/misc.ts
> +  return '0x' + '0'.repeat(byteLength * 2 - baseString.length) + baseString.toLowerCase();
Codacy has a fix for the issue: [Replace `'0x'·+·'0'.repeat(byteLength·*·2·-·baseString.length)·+·baseString.toLowerCase()` with `(⏎····"0x"·+⏎····"0".repeat(byteLength·*·2·-·baseString.length)·+⏎····baseString.toLowerCase()⏎··)`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
  return (
```

2022-07-21 13:57 UTC, cwteles commented on test/periphery/CardPaymentProcessorUpgradeable.test.ts
> +  const REVERT_MESSAGE_IF_PAYMENT_AMOUNT_IS_ZERO = 'CardPaymentProcessor: payment amount must be greater than 0';
Codacy has a fix for the issue: [Replace `·'CardPaymentProcessor:·payment·amount·must·be·greater·than·0'` with `⏎····"CardPaymentProcessor:·payment·amount·must·be·greater·than·0"`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
  const REVERT_MESSAGE_IF_PAYMENT_AMOUNT_IS_ZERO =
```

2022-07-21 13:57 UTC, cwteles commented on test-utils/misc.ts
> +      + `The length of the base string if greater than allowed maximum length. `
Codacy has a fix for the issue: [Replace `+·`The·length·of·the·base·string·if·greater·than·allowed·maximum·length.·`` with `··`The·length·of·the·base·string·if·greater·than·allowed·maximum·length.·`·+`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
        `The length of the base string if greater than allowed maximum length. ` +
```

2022-07-21 13:57 UTC, cwteles commented on test/periphery/CardPaymentProcessorUpgradeable.test.ts
> +  const REVERT_MESSAGE_IF_CALLER_IS_NOT_OWNER = "Ownable: caller is not the owner";
Codacy has a fix for the issue: [Insert `⏎···`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
  const REVERT_MESSAGE_IF_CALLER_IS_NOT_OWNER =
```

2022-07-21 13:57 UTC, cwteles commented on test/periphery/CardPaymentProcessorUpgradeable.test.ts
> +  const REVERT_MESSAGE_IF_TOKEN_TRANSFER_AMOUNT_EXCEEDS_BALANCE = "ERC20: transfer amount exceeds balance";
Codacy has a fix for the issue: [Insert `⏎···`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
  const REVERT_MESSAGE_IF_TOKEN_TRANSFER_AMOUNT_EXCEEDS_BALANCE =
```

2022-07-21 13:57 UTC, cwteles commented on test-utils/misc.ts
> +      `Creating of bytes string failed. `
Codacy has a fix for the issue: [Insert `·+`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
      `Creating of bytes string failed. ` +
```

2022-07-21 13:57 UTC, cwteles commented on test/periphery/CardPaymentProcessorUpgradeable.test.ts
> +  revocationCounter?: number,
Codacy has a fix for the issue: [Replace `,` with `;`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
  revocationCounter?: number;
```

2022-07-21 13:57 UTC, cwteles commented on test-utils/misc.ts
> +      `Creating of bytes16 string failed. `
Codacy has a fix for the issue: [Insert `·+`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
      `Creating of bytes16 string failed. ` +
```

2022-07-21 13:57 UTC, cwteles commented on test/periphery/CardPaymentProcessorUpgradeable.test.ts
> +  account: SignerWithAddress,
Codacy has a fix for the issue: [Replace `,` with `;`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
  account: SignerWithAddress;
```

2022-07-21 14:34 UTC, cwteles commented on test/periphery/CardPaymentProcessorUpgradeable.test.ts
> +    const expectedState: CardPaymentProcessorState = defineExpectedCardPaymentProcessorState(payments);
Codacy has a fix for the issue: [Insert `⏎·····`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
    const expectedState: CardPaymentProcessorState =
```

2022-07-21 14:34 UTC, cwteles commented on test/periphery/CardPaymentProcessorUpgradeable.test.ts
> +      await setUpContractsForPayments([payment])
Codacy has a fix for the issue: [Insert `;`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
      await setUpContractsForPayments([payment]);
```

2022-07-21 14:34 UTC, cwteles commented on test/periphery/CardPaymentProcessorUpgradeable.test.ts
> +      payments.forEach(payment => payment.status = PaymentStatus.Confirmed)
Codacy has a fix for the issue: [Replace `(payment·=>·payment.status·=·PaymentStatus.Confirmed)` with `((payment)·=>·(payment.status·=·PaymentStatus.Confirmed));`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
      payments.forEach((payment) => (payment.status = PaymentStatus.Confirmed));
```

2022-07-21 14:34 UTC, cwteles commented on test/periphery/CardPaymentProcessorUpgradeable.test.ts
> +    const BRLCMock: ContractFactory = await ethers.getContractFactory("ERC20UpgradeableMock");
Codacy has a fix for the issue: [Replace `"ERC20UpgradeableMock"` with `⏎······"ERC20UpgradeableMock"⏎····`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
    const BRLCMock: ContractFactory = await ethers.getContractFactory(
```

2022-07-21 14:34 UTC, cwteles commented on test/periphery/CardPaymentProcessorUpgradeable.test.ts
> +        reversingPaymentCorrelationId,
Codacy has a fix for the issue: [Insert `····`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
            reversingPaymentCorrelationId,
```

2022-07-21 14:34 UTC, cwteles commented on test/periphery/CardPaymentProcessorUpgradeable.test.ts
> +      await expect(cardPaymentProcessor.connect(deployer).reversePayment(
Codacy has a fix for the issue: [Replace `cardPaymentProcessor.connect(deployer)` with `⏎········cardPaymentProcessor⏎··········.connect(deployer)⏎··········`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
      await expect(
```

2022-07-21 14:34 UTC, cwteles commented on test/periphery/CardPaymentProcessorUpgradeable.test.ts
> +        createBytesString(payment.authorizationId + 1, BYTES16_LENGTH)
Codacy has a fix for the issue: [Insert `····`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
            createBytesString(payment.authorizationId + 1, BYTES16_LENGTH)
```

2022-07-21 14:34 UTC, cwteles commented on test/periphery/CardPaymentProcessorUpgradeable.test.ts
> +        parentTxHash: parentTxHash
Codacy has a fix for the issue: [Insert `,`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
        parentTxHash: parentTxHash,
```

2022-07-21 14:34 UTC, cwteles commented on test/periphery/CardPaymentProcessorUpgradeable.test.ts
> +      expectedClearedBalances = payments.map(payment => payment.amount);
Codacy has a fix for the issue: [Replace `payment` with `(payment)`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
      expectedClearedBalances = payments.map((payment) => payment.amount);
```

2022-07-21 14:34 UTC, cwteles commented on test/periphery/CardPaymentProcessorUpgradeable.test.ts
> +    const totalUnclearedBalance: number = payments.map(function (payment: TestPayment): number {
Codacy has a fix for the issue: [Insert `⏎······`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
    const totalUnclearedBalance: number = payments
```

2022-07-21 14:34 UTC, cwteles commented on test/periphery/CardPaymentProcessorUpgradeable.test.ts
> +      await expect(cardPaymentProcessor.makePayment(
Codacy has a fix for the issue: [Insert `⏎········`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
      await expect(
```

2022-07-21 14:34 UTC, cwteles commented on test/periphery/CardPaymentProcessorUpgradeable.test.ts
> +    const tokenBalance: number = payments.map(function (payment: TestPayment): number {
Codacy has a fix for the issue: [Insert `⏎······`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
    const tokenBalance: number = payments
```

2022-07-21 14:34 UTC, cwteles commented on test/periphery/CardPaymentProcessorUpgradeable.test.ts
> +        authorizationIds[0],
Codacy has a fix for the issue: [Insert `··`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
          authorizationIds[0],
```

2022-07-21 14:34 UTC, cwteles commented on test/periphery/CardPaymentProcessorUpgradeable.test.ts
> +        );
Codacy has a fix for the issue: [Replace `);` with `expect(`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
        expect(
```

2022-07-21 14:34 UTC, cwteles commented on test/periphery/CardPaymentProcessorUpgradeable.test.ts
> +    })
Codacy has a fix for the issue: [Insert `;`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
    });
```

2022-07-21 14:34 UTC, cwteles commented on test/periphery/CardPaymentProcessorUpgradeable.test.ts
> +        payments[1].revocationCounter || 0
Codacy has a fix for the issue: [Insert `··`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
          payments[1].revocationCounter || 0
```

2022-07-21 14:34 UTC, cwteles commented on test/periphery/CardPaymentProcessorUpgradeable.test.ts
> +          expectedRevocationCounter
Codacy has a fix for the issue: [Insert `··`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
            expectedRevocationCounter
```

2022-07-21 14:34 UTC, cwteles commented on test-utils/misc.ts
> +      `The base string: '${baseString}'`
Codacy has a fix for the issue: [Insert `··`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
        `The base string: '${baseString}'`
```

2022-07-21 14:34 UTC, cwteles commented on test/periphery/CardPaymentProcessorUpgradeable.test.ts
> +        payment.account.address,
Codacy has a fix for the issue: [Insert `··`](https://app.codacy.com/gh/cloudwalk/brlc-token/pullRequest?prid=9781596)
```suggestion
          payment.account.address,
```

2022-07-26 11:18 UTC, igorsenych-cw approved these changes

2022-07-26 11:20 UTC, merged