improve docs and style
cloudwalk/brlc-token pull request #18
Opened 2022-07-21 18:05 UTC by arthur-cw

2022-07-21 18:25 UTC, EvgeniiZaitsevCW requested changes

2022-07-21 18:25 UTC, EvgeniiZaitsevCW commented on .github/workflows/build.yml
> +  ubuntu-latest:
Replace "ubuntu-latest" => "compile_contracts"

2022-07-21 18:25 UTC, EvgeniiZaitsevCW commented on .github/workflows/test.yml
> +  ubuntu-latest:
Rename "ubuntu-latest" => "run_contracts_tests"

2022-07-21 18:25 UTC, EvgeniiZaitsevCW commented on .github/workflows/build.yml
> +    branches: "**"
Here and in the same place of the `test.yaml` file.
Maybe it is better to leave only `main` branch here.

2022-07-21 18:27 UTC, arthur-cw commented on .github/workflows/build.yml
> +  ubuntu-latest:
we want the name of the job to show the system :-)

2022-07-21 18:27 UTC, arthur-cw commented on .github/workflows/build.yml
> +  ubuntu-latest:
![image](https://user-images.githubusercontent.com/70960269/180286911-80d2afe9-9f57-4edc-8181-455a2c03a3ba.png)

2022-07-21 18:30 UTC, EvgeniiZaitsevCW approved these changes

2022-07-21 18:30 UTC, EvgeniiZaitsevCW commented on .github/workflows/build.yml
> +  ubuntu-latest:
Got it! Thanks

2022-07-21 18:30 UTC, EvgeniiZaitsevCW commented on .github/workflows/build.yml
> +    branches: "**"
Ok. We can change it later.

2022-07-23 10:29 UTC, EvgeniiZaitsevCW approved these changes

2022-07-23 10:29 UTC, EvgeniiZaitsevCW commented on .gitignore
> +.openzeppelin/unknown-*.json
I don't think it is a good idea.
We at least need to save `.openzeppelin/unknown-2009.json` for our `Mainnet`.

2022-07-23 10:32 UTC, EvgeniiZaitsevCW requested changes

2022-07-23 10:32 UTC, EvgeniiZaitsevCW commented on .gitignore
> +.openzeppelin/unknown-*.json
I don't think it is a good idea.
We at least need to save `.openzeppelin/unknown-2009.json` for our `Mainnet`.

2022-07-23 16:05 UTC, arthur-cw commented on .gitignore
> +.openzeppelin/unknown-*.json
maybe we should change the file's name :thinking:  usually files with the `unknown` substring are used for development, check [here](https://docs.openzeppelin.com/upgrades-plugins/1.x/network-files#configuration-files-in-version-control)

2022-07-23 16:27 UTC, EvgeniiZaitsevCW commented on .gitignore
> +.openzeppelin/unknown-*.json
I agree

2022-07-25 05:02 UTC, EvgeniiZaitsevCW approved these changes

2022-07-25 10:26 UTC, igorsenych-cw approved these changes

2022-07-25 10:27 UTC, merged